---
- name: WebServers to deploy to
  hosts: all
  remote_user: ec2-user
  tasks:

  - name: Installing Http Package
    yum:
      name: httpd
      state: installed

  - name: Opening port "443"
    firewalld:
      service: https
      permanent: true
      state: enabled

  - name: restart firewalld
    service:
      name: firewalld
      state: restarted

  - name: Generate a Self Signed OpenSSL certificate
      community.crypto.x509_certificate:
        path: /etc/ssl/crt/ansible.com.crt
        privatekey_path: /etc/ssl/private/ansible.com.pem
        csr_path: /etc/ssl/csr/ansible.com.csr
        provider: selfsigned

  - name: Copying document root
      copy:
        src: ~/tmp2/index.html
        dest: /var/www/html/
        owner: root
        group: root
        mode: 0755

  - name: starting httpd
      service:
        name: httpd
        state: restarted
        enabled: yes
